### PR TITLE
Added two new scenarios: HR Web App and Spark with Scone

### PR DESCRIPTION
**Pull request by mdrakiburrahman**
1) Confidential Analytics with Spark and Azure SQL
2) Confidential Web Application Hosting - End-to-end

## Purpose

* Added two new scenarios: HR Web App and Spark with Scone

## Does this introduce a breaking change?

```
[ ] Yes
[X ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[X ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by mdrakiburrahman** [comment]
@agowdamsft

**Comment by agowdamsft** [comment]
#sign-off

**Comment by praenubilus** [comment]
@mdrakiburrahman can you add some instructions on how to test the sample?

**Comment by agowdamsft** [comment]
Please PR only the apache spark with AKS deployment sample

**Pull request closed without merging**
